<a href="https://cognitiveclass.ai/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDL0101ENSkillsNetwork945-2022-01-01"><img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DL0101EN-SkillsNetwork/images/IDSN-logo.png" width="400"> </a>

<h1 align=center><font size = 5>Convolutional Neural Networks with Keras</font></h1>


In this lab, we will learn how to use the Keras library to build convolutional neural networks. We will also use the popular MNIST dataset and we will compare our results to using a conventional neural network.


<h2>Convolutional Neural Networks with Keras</h2>

<h3>Objective for this Notebook<h3>    
<h5> 1. How to use the Keras library to build convolutional neural networks.</h5>
<h5> 2. Convolutional Neural Network with One Convolutional and Pooling Layers.</h5>
<h5> 3. Convolutional Neural Network with Two Convolutional and Pooling Layers.</h5>



## Table of Contents

<div class="alert alert-block alert-info" style="margin-top: 20px">

<font size = 3>
      
1. <a href="#item41">Import Keras and Packages</a>   
2. <a href="#item42">Convolutional Neural Network with One Convolutional and Pooling Layers</a>  
3. <a href="#item43">Convolutional Neural Network with Two Convolutional and Pooling Layers</a>  

</font>
</div>


<a id='item41'></a>


## Import Keras and Packages


Let's start by importing the keras libraries and the packages that we would need to build a neural network.


In [1]:
# All Libraries required for this lab are listed below. The libraries pre-installed on Skills Network Labs are commented. 
# If you run this notebook on a different environment, e.g. your desktop, you may need to uncomment and install certain libraries.

#!pip install numpy==1.21.4
#!pip install pandas==1.3.4
#!pip install keras==2.1.6

In [57]:
import keras
from keras.models import Sequential
from keras.layers import Dense
from keras.utils import to_categorical
import numpy as np
import pandas as pd

When working with convolutional neural networks in particular, we will need additional packages.


In [58]:
from keras.layers.convolutional import Conv2D # to add convolutional layers
from keras.layers.convolutional import MaxPooling2D # to add pooling layers
from keras.layers import Flatten # to flatten data for fully connected layers

<a id='item42'></a>


## Convolutional Layer with One set of convolutional and pooling layers


In [68]:
# import data
from keras.datasets import mnist

# load data
(X_train, y_train), (X_test, y_test) = mnist.load_data()

print(f'X train shape : {X_train.shape}')
print(f'Y train shape : {y_train.shape}')
print(f'X test shape  : {X_test.shape}')
print(f'Y test shape  : {y_test.shape}')
print()

# reshape to be [samples][pixels][width][height]
X_train = X_train.reshape(X_train.shape[0], 28, 28, 1).astype('float32')
X_test = X_test.reshape(X_test.shape[0], 28, 28, 1).astype('float32')

print('Reshape X train and test to be [number of images][pixels][width][height]')
print('The X train and test data after reshaping :-')
print(f'X train shape : {X_train.shape}')
print(f'X test shape  : {X_test.shape}')

X train shape : (60000, 28, 28)
Y train shape : (60000,)
X test shape  : (10000, 28, 28)
Y test shape  : (10000,)

Reshape X train and test to be [number of images][pixels][width][height]
The X train and test data after reshaping :-
X train shape : (60000, 28, 28, 1)
X test shape  : (10000, 28, 28, 1)


Let's normalize the pixel values to be between 0 and 1


In [69]:
print(f'The maximum number of X train dataset is : {X_train.max()}')
print(f'The minimum number of X train dataset is : {X_train.min()}')
print(f'The mean number    of X train dataset is : {X_train.mean()}')
print(f'The maximum number of X test dataset is  : {X_test.max()}')
print(f'The minimum number of X test dataset is  : {X_test.min()}')
print(f'The mean number    of X test dataset is  : {X_test.mean()}')
print()

print('We need to normalize the datasets, to make the pixel values between 0 and 1.')
X_train = X_train / 255 # normalize training data
X_test = X_test / 255 # normalize test data

print('\nThe datasets after normalization :-')
print(f'The maximum number of X train dataset is : {X_train.max()}')
print(f'The minimum number of X train dataset is : {X_train.min()}')
print(f'The mean number    of X train dataset is : {X_train.mean()}')
print(f'The maximum number of X test dataset is  : {X_test.max()}')
print(f'The minimum number of X test dataset is  : {X_test.min()}')
print(f'The mean number    of X test dataset is  : {X_test.mean()}')

The maximum number of X train dataset is : 255.0
The minimum number of X train dataset is : 0.0
The mean number    of X train dataset is : 33.31844711303711
The maximum number of X test dataset is  : 255.0
The minimum number of X test dataset is  : 0.0
The mean number    of X test dataset is  : 33.79124069213867

We need to normalize the datasets, to make the pixel values between 0 and 1.

The datasets after normalization :-
The maximum number of X train dataset is : 1.0
The minimum number of X train dataset is : 0.0
The mean number    of X train dataset is : 0.13066062331199646
The maximum number of X test dataset is  : 1.0
The minimum number of X test dataset is  : 0.0
The mean number    of X test dataset is  : 0.13251467049121857


Next, let's convert the target variable into binary categories


In [70]:
unique, counts = np.unique(y_train, return_counts=True)
print('Y train classes and their counts :-')
print(np.asarray((unique, counts)).T)

print()

print('Y test classes and their counts :-')
unique, counts = np.unique(y_test, return_counts=True)
print(np.asarray((unique, counts)).T)

Y train classes and their counts :-
[[   0 5923]
 [   1 6742]
 [   2 5958]
 [   3 6131]
 [   4 5842]
 [   5 5421]
 [   6 5918]
 [   7 6265]
 [   8 5851]
 [   9 5949]]

Y test classes and their counts :-
[[   0  980]
 [   1 1135]
 [   2 1032]
 [   3 1010]
 [   4  982]
 [   5  892]
 [   6  958]
 [   7 1028]
 [   8  974]
 [   9 1009]]


In [71]:
print('One hot encoding to Y train and test :-')
print()

y_train = to_categorical(y_train)
y_test = to_categorical(y_test)

print('Y train after encoding :-')
print(y_train)
print(y_train.shape)
print()
print('Y test after encoding :-')
print(y_test)
print(y_test.shape)

num_classes = y_test.shape[1] # number of categories

One hot encoding to Y train and test :-

Y train after encoding :-
[[0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]]
(60000, 10)

Y test after encoding :-
[[0. 0. 0. ... 1. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
(10000, 10)


Next, let's define a function that creates our model. Let's start with one set of convolutional and pooling layers.


In [72]:
def convolutional_model():
    
    # create model
    model = Sequential()
    
    model.add(Conv2D(16, (5, 5), strides=(1, 1), activation='relu', input_shape=(28, 28, 1)))
    model.add(MaxPooling2D(pool_size=(2, 2), strides=(2, 2)))
    
    model.add(Flatten())
    model.add(Dense(100, activation='relu'))
    model.add(Dense(num_classes, activation='softmax'))
    
    # compile model
    model.compile(optimizer='adam', loss='categorical_crossentropy',  metrics=['accuracy'])
    return model

Finally, let's call the function to create the model, and then let's train it and evaluate it.


In [73]:
# build the model
model = convolutional_model()

# fit the model
model.fit(X_train, y_train, validation_data=(X_test, y_test), epochs=10, batch_size=200, verbose=2)

# evaluate the model
scores = model.evaluate(X_test, y_test, verbose=0)
print("Accuracy: {} \n Error: {}".format(scores[1], 100-scores[1]*100))

Epoch 1/10
300/300 - 6s - loss: 0.2737 - accuracy: 0.9275 - val_loss: 0.0921 - val_accuracy: 0.9727 - 6s/epoch - 19ms/step
Epoch 2/10
300/300 - 5s - loss: 0.0784 - accuracy: 0.9773 - val_loss: 0.0588 - val_accuracy: 0.9807 - 5s/epoch - 16ms/step
Epoch 3/10
300/300 - 5s - loss: 0.0549 - accuracy: 0.9836 - val_loss: 0.0465 - val_accuracy: 0.9841 - 5s/epoch - 16ms/step
Epoch 4/10
300/300 - 5s - loss: 0.0432 - accuracy: 0.9872 - val_loss: 0.0458 - val_accuracy: 0.9843 - 5s/epoch - 16ms/step
Epoch 5/10
300/300 - 5s - loss: 0.0356 - accuracy: 0.9894 - val_loss: 0.0403 - val_accuracy: 0.9858 - 5s/epoch - 16ms/step
Epoch 6/10
300/300 - 5s - loss: 0.0287 - accuracy: 0.9914 - val_loss: 0.0387 - val_accuracy: 0.9867 - 5s/epoch - 16ms/step
Epoch 7/10
300/300 - 5s - loss: 0.0243 - accuracy: 0.9927 - val_loss: 0.0379 - val_accuracy: 0.9858 - 5s/epoch - 16ms/step
Epoch 8/10
300/300 - 5s - loss: 0.0204 - accuracy: 0.9939 - val_loss: 0.0402 - val_accuracy: 0.9859 - 5s/epoch - 16ms/step
Epoch 9/10
300/3

------------------------------------------


<a id='item43'></a>


## Convolutional Layer with two sets of convolutional and pooling layers


Let's redefine our convolutional model so that it has two convolutional and pooling layers instead of just one layer of each.


In [74]:
def convolutional_model():
    
    # create model
    model = Sequential()
    
    model.add(Conv2D(16, (5, 5), activation='relu', input_shape=(28, 28, 1)))
    model.add(MaxPooling2D(pool_size=(2, 2), strides=(2, 2)))
    
    model.add(Conv2D(8, (2, 2), activation='relu'))
    model.add(MaxPooling2D(pool_size=(2, 2), strides=(2, 2)))
    
    model.add(Flatten())
    model.add(Dense(100, activation='relu'))
    model.add(Dense(num_classes, activation='softmax'))
    
    # Compile model
    model.compile(optimizer='adam', loss='categorical_crossentropy',  metrics=['accuracy'])
    return model

Now, let's call the function to create our new convolutional neural network, and then let's train it and evaluate it.


In [75]:
# build the model
model = convolutional_model()

# fit the model
model.fit(X_train, y_train, validation_data=(X_test, y_test), epochs=10, batch_size=200, verbose=2)

# evaluate the model
scores = model.evaluate(X_test, y_test, verbose=0)
print("Accuracy: {} \n Error: {}".format(scores[1], 100-scores[1]*100))

Epoch 1/10
300/300 - 6s - loss: 0.5207 - accuracy: 0.8477 - val_loss: 0.1678 - val_accuracy: 0.9498 - 6s/epoch - 20ms/step
Epoch 2/10
300/300 - 5s - loss: 0.1296 - accuracy: 0.9610 - val_loss: 0.0819 - val_accuracy: 0.9754 - 5s/epoch - 17ms/step
Epoch 3/10
300/300 - 5s - loss: 0.0891 - accuracy: 0.9721 - val_loss: 0.0660 - val_accuracy: 0.9801 - 5s/epoch - 17ms/step
Epoch 4/10
300/300 - 5s - loss: 0.0692 - accuracy: 0.9783 - val_loss: 0.0552 - val_accuracy: 0.9822 - 5s/epoch - 17ms/step
Epoch 5/10
300/300 - 5s - loss: 0.0574 - accuracy: 0.9826 - val_loss: 0.0471 - val_accuracy: 0.9839 - 5s/epoch - 17ms/step
Epoch 6/10
300/300 - 5s - loss: 0.0497 - accuracy: 0.9849 - val_loss: 0.0423 - val_accuracy: 0.9853 - 5s/epoch - 17ms/step
Epoch 7/10
300/300 - 5s - loss: 0.0440 - accuracy: 0.9865 - val_loss: 0.0439 - val_accuracy: 0.9851 - 5s/epoch - 17ms/step
Epoch 8/10
300/300 - 5s - loss: 0.0405 - accuracy: 0.9872 - val_loss: 0.0420 - val_accuracy: 0.9862 - 5s/epoch - 17ms/step
Epoch 9/10
300/3

### Thank you for completing this lab!

This notebook was created by [Alex Aklson](https://www.linkedin.com/in/aklson/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDL0101ENSkillsNetwork945-2022-01-01). I hope you found this lab interesting and educational. Feel free to contact me if you have any questions!



## Change Log

|  Date (YYYY-MM-DD) |  Version | Changed By  |  Change Description |
|---|---|---|---|
| 2020-09-21  | 2.0  | Srishti  |  Migrated Lab to Markdown and added to course repo in GitLab |



<hr>

## <h3 align="center"> © IBM Corporation 2020. All rights reserved. <h3/>


This notebook is part of a course on **Coursera** called *Introduction to Deep Learning & Neural Networks with Keras*. If you accessed this notebook outside the course, you can take this course online by clicking [here](https://cocl.us/DL0101EN_Coursera_Week4_LAB1).


<hr>

Copyright &copy; 2019 [IBM Developer Skills Network](https://cognitiveclass.ai/?utm_medium=dswb&utm_source=bducopyrightlink&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDL0101ENSkillsNetwork945-2022-01-01&utm_campaign=bdu). This notebook and its source code are released under the terms of the [MIT License](https://bigdatauniversity.com/mit-license/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDL0101ENSkillsNetwork945-2022-01-01).
